### ISSUE TITLE
Group Synergy Cooldown Tracking

### ISSUE THREAD

**Issue by Bjornie** [Bjornie/BearSynergies#3]
- [ ] Group Cooldown Tracking
- [ ] Flair For Alkosh Wearer
- [ ] Alert If No Alkosh On Boss And Synergy Off CD For Alkosh Wearer
- [ ] Alkosh Timer For Alkosh Wearer
